config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :registers
  resources :conta
  devise_scope :user do
    authenticated do
      root 'registers#index'
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
#  get '/articles', to: 'articles#index'
#  get '/articles/:id', to: 'articles#show'

  
  resources :articles #chamando resources
end

app/models/register.rb
class Register < ApplicationRecord
#    belongs_to :conta
    belongs_to :user
    validates :tipo, presence: true
    validates :valor, presence: true, numericality: {only_float: true, :greater_than => 0}
    validates :saldo, numericality: {only_float: true, :greater_than => 0}

    scope :filter_by_registermensal, lambda { |month_year|
        if month_year
          date = Date.strptime(month_year, '%B %Y')
          where created_at: date.beginning_of_month..date.end_of_month.next_day
        end
    }

end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  before_action :authenticate_user!, except: %i[ index ]
  before_action :set_register, only: %i[ show edit update destroy ]

  # GET /registers or /registers.json
  def index
    @registers = current_user.register.all.filter_by_registermensal(params[:month_year])
    @registermensal = current_user.register.group_by_month(:created_at, format: '%B %Y').count
#  @highlights = Register.filter_register(params[:session])
  end

  # GET /registers/1 or /registers/1.json
  def show
  end

  # GET /registers/new
  def new
    @register = current_user.register.new
  end

  # GET /registers/1/edit
  def edit
  end

  # POST /registers or /registers.json
  def create
    @register = current_user.register.new(register_params)
    
    if @register.valor 
      if @register.tipo=='Deposito'
        @register.saldo = current_user.saldo + @register.valor
        current_user.saldo += @register.valor
        current_user.save
      end
      if @register.tipo=='Saque' or @register.tipo=='Transferencia'
        if  @register.tipo=='Transferencia'
          @usuario = User.find(@register.transferir)
          @usuario.saldo += @register.valor
          @usuario.save
          @registerRecebedor = @usuario.register.new(register_params)
          @registerRecebedor.user_id = @usuario.id
          @registerRecebedor.saldo = @usuario.saldo + @registerRecebedor.valor
          @registerRecebedor.save
          @register.saldo = current_user.saldo - @register.valor
          current_user.saldo -= @register.valor
          current_user.save
        else
          @register.saldo = current_user.saldo - @register.valor
          current_user.saldo -= @register.valor
          current_user.save
        end
      end
    end

    respond_to do |format|
      if @register.save
        if @register.tipo=='Transferencia'
          if (datahour(@register.created_at) >= '9' and datahour(@register.created_at) <= '18') and (dataday(@register.created_at) == 'Monday' or 'Tuesday' or 'Wednesday' or'Thursday' or 'Friday')
            current_user.saldo -= 5
          else
            current_user.saldo -= 7
          end
          if @register.valor > 1000
            current_user.saldo -= 10
          end
          current_user.save
        end
        format.html { redirect_to register_url(@register), notice: "Register was successfully created." }
        format.json { render :show, status: :created, location: @register }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registers/1 or /registers/1.json
  def update
    respond_to do |format|
      if @register.update(register_params)
        format.html { redirect_to register_url(@register), notice: "Register was successfully updated." }
        format.json { render :show, status: :ok, location: @register }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registers/1 or /registers/1.json
  def destroy
    @register.destroy

    respond_to do |format|
      format.html { redirect_to registers_url, notice: "Register was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_register
      @register = Register.find(params[:id])
    end

    
    def dataday(datetime)
      datetime.strftime('%A')
    end
    def datahour(datetime)
        datetime.strftime('%-H')
    end

    # Only allow a list of trusted parameters through.
    def register_params
      params.require(:register).permit(:tipo, :descricao, :valor, :transferir)
    end
end

app/helpers/registers_helper.rb
module RegistersHelper
    def datacao(datetime)
        datetime.strftime('%e / %m / %Y')
    end
    def dataday(datetime)
        datetime.strftime('%A')
    end
    def datahour(datetime)
        datetime.strftime('%-H')
    end
end

app/views/registers/_form.html.erb
<%= form_with(model: register) do |form| %>
  <% if register.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(register.errors.count, "error") %> prohibited this register from being saved:</h2>

      <ul>
        <% register.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <h5>Saldo: <%=current_user.saldo %></h5>
  </div>

  <%= form.select :tipo, [["Depositar", "Deposito"], ["Sacar", "Saque"], ["Transferir", "Transferencia"]] %>

  

<!--
  <div>
    <%= form.label :tipo, style: "display: block" %>
    <%= form.text_field :tipo %>
  </div>
-->
  <div>
    <%= form.label :descricao, style: "display: block" %>
    <%= form.text_field :descricao %>
  </div>

  <div>
    <%= form.label :valor, style: "display: block" %>
    <%= form.text_field :valor %>
  </div>
<!--
  <div>
    <%= form.label :saldo, style: "display: block" %>
    <%= form.text_field :saldo %>
  </div>
-->

  <div>
    <%= form.label :'ID usuario a receber', style: "display: block" %>
    <%= form.text_field :transferir %>
  </div>

  <div style="margin-top:1em">
    <%= form.submit %>
  </div>
<% end %>

app/views/registers/_register.html.erb
<div id="<%= dom_id register %>" style="display: flex">

  <p style="margin: 1em"><%= datacao(register.created_at) %></p>

  <p style="margin: 1em">
    <strong>Tipo:</strong>
    <%= register.tipo %>
  </p>

  <p style="margin: 1em">
    <strong>Descricao:</strong>
    <%= register.descricao %>
  </p>

  <p style="margin: 1em">
    <strong>Valor:</strong>
    <%= register.valor %>
  </p>

  <p style="margin: 1em">
    <strong>Saldo:</strong>
    <%= register.saldo %>
  </p>

  <p style="margin: 1em">
    <strong>Transferencia:</strong>
    <%= register.transferir %>
  </p>

</div>

app/views/registers/_registermensal.html.erb
<center>
    <div class="border border-3" style="margin-left: 1.5em">
        <h4 class="fst-italic">Meses</h4>
        <ol class="list-unstyled mb-0">
            <% @registermensal.each do |month_year, count| %>
                
                <li>
                    <%= link_to "#{month_year}(#{count})", registers_path(month_year: month_year),
                        class:"p-2 link-secondary #{'filter-registermensal' if month_year == params[:month_year]}" %>
                </li>

            <% end %>
        </ol>
  </div>
</center>

app/views/registers/edit.html.erb
<center>
  <h1>Editing register</h1>
  <% if @register.user_id == current_user.id %>
    <%= render "form", register: @register %>
    <br>
    <div>
      <%= link_to "Show this register", @register %> |
      <%= link_to "Back to registers", registers_path %>
    </div>
  <% else %>
    <h4>Esse registro não pertence a esse Usuario</h4>
  <% end %>
</center>

app/views/registers/index.html.erb
<p style="color: green"><%= notice %></p>
<center>
<h1 style="display: inline">Registers</h1>
<%= link_to 'Novo', new_register_path, class: 'btn btn-secondary', style:"margin: 0 1em 1em 1em" %> <!-- chamar view para novo -->
</center>
<div  style="display:flex">
  <div style="width: 200px;"> <%= render 'registermensal' %> </div>
  <div id="registers" style="margin: 0 1.5em; width: 1250px;">
    <% @registers.each do |register| %>
      <% if register.user_id == current_user.id %>
        <div style="display: flex; margin-bottom: 1em;" class="border border-2">
          <%= render register %>
          <p  style="margin: 0.5em">
            <%= link_to "Abrir", register, class: 'btn btn-secondary' %>
          </p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/registers/new.html.erb
<center>
<div style="border:solid; max-width:250px; margin: 1em">
  <h1 style="margin: 10px 0">New register</h1>

  <%= render "form", register: @register %>

  <div style="margin: 10px 0">
    <%= link_to "Back to registers", registers_path, class: 'btn btn-secondary' %>
  </div>
</center>

app/views/registers/show.html.erb
<!--<p style="color: green"><%= notice %></p>-->
<center style="margin: 1em 2em">
    <% if @register.user_id == current_user.id %>
      <h1>ID usuario: <%= @register.user_id %></h1>
      
      <div style="display: flex;margin:1em" class="border border-2">
      <%= render @register %>
<!--      <div style="margin-top: 1em"><%= link_to "Edit this register", edit_register_path(@register), class: 'btn btn-secondary', style:"margin-right: 1em"%></div>
      <div style="margin-top: 1em"><%= button_to "Destroy this register", @register, method: :delete, class: 'btn btn-danger' %></div>-->
      <div style="margin-top: 0.5em;"><%= link_to "Back to registers", registers_path, class: 'btn btn-secondary' %></div></div>
    <% else %>
      <h4>Esse registro não pertence a esse Usuario</h4>
    <% end %>
</center>