config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :registers
  resources :conta
  devise_scope :user do
    authenticated do
      root 'registers#index'
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
#  get '/articles', to: 'articles#index'
#  get '/articles/:id', to: 'articles#show'

  
  resources :articles #chamando resources
end

app/controllers/conta_controller.rb
class ContaController < ApplicationController
  before_action :set_contum, only: %i[ show edit update destroy ]

  # GET /conta or /conta.json
  def index
    @conta = Contum.all
  end

  # GET /conta/1 or /conta/1.json
  def show
  end

  # GET /conta/new
  def new
    @contum = Contum.new
  end

  # GET /conta/1/edit
  def edit
  end

  # POST /conta or /conta.json
  def create
    @contum = Contum.new(contum_params)

    respond_to do |format|
      if @contum.save
        format.html { redirect_to contum_url(@contum), notice: "Contum was successfully created." }
        format.json { render :show, status: :created, location: @contum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conta/1 or /conta/1.json
  def update
    respond_to do |format|
      if @contum.update(contum_params)
        format.html { redirect_to contum_url(@contum), notice: "Contum was successfully updated." }
        format.json { render :show, status: :ok, location: @contum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conta/1 or /conta/1.json
  def destroy
    @contum.destroy

    respond_to do |format|
      format.html { redirect_to conta_url, notice: "Contum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contum
      @contum = Contum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contum_params
      params.require(:contum).permit(:nome, :cpf, :senha, :tipo, :saldo)
    end
end

app/helpers/conta_helper.rb
module ContaHelper
    def datacao(datetime)
        datetime.strftime('%H:%M:%S, %e / %B / %Y')
    end
end

app/views/conta/_contum.html.erb
<div id="<%= dom_id contum %>">
  <p>
    <strong>Nome:</strong>
    <%= contum.nome %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= contum.cpf %>
  </p>

  <p>
    <strong>Senha:</strong>
    <%= contum.senha %>
  </p>

  <p>
    <strong>Tipo:</strong>
    <%= contum.tipo %>
  </p>

  <p>
    <strong>Saldo:</strong>
    <%= contum.saldo %>
  </p>

</div>

app/views/conta/_form.html.erb
<%= form_with(model: contum) do |form| %>
  <% if contum.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contum.errors.count, "error") %> prohibited this contum from being saved:</h2>

      <ul>
        <% contum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :senha, style: "display: block" %>
    <%= form.text_field :senha %>
  </div>

  <div>
    <%= form.label :tipo, style: "display: block" %>
    <%= form.text_field :tipo %>
  </div>

  <div>
    <%= form.label :saldo, style: "display: block" %>
    <%= form.text_field :saldo %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/conta/edit.html.erb
<h1>Editing contum</h1>

<%= render "form", contum: @contum %>

<br>

<div>
  <%= link_to "Show this contum", @contum %> |
  <%= link_to "Back to conta", conta_path %>
</div>

app/views/conta/index.html.erb
<!--<p style="color: green"><%= notice %></p>-->
<center>
  <h1 style="display: inline">Contas</h1>
  <%= link_to 'Novo', new_contum_path, class: 'btn btn-secondary', style:"margin: 0 1em 1em 1em" %> <!-- chamar view para novo -->
</center>
<div class="container">
<div id="conta" class="row">
  <% @conta.each do |contum| %>
    <div class="card" style="max-width:20%">
      <div class="card-body">
        <%= render contum %>
        <p>
          <%= link_to "Show this contum", contum %>
        </p>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/conta/new.html.erb
<h1>New contum</h1>

<%= render "form", contum: @contum %>

<br>

<div>
  <%= link_to "Back to conta", conta_path %>
</div>

app/views/conta/show.html.erb
<!--<p style="color: green"><%= notice %></p>-->
<h4>Conta <%= @contum.id %> </h4>
<%= render @contum %>

<div>
  <%= link_to "Edit this contum", edit_contum_path(@contum) %> |
  <%= link_to "Back to conta", conta_path %>

  <%= button_to "Destroy this contum", @contum, method: :delete %>
</div>
<br>
<%= link_to 'Nova Transação', new_article_path, class: 'btn btn-secondary', style:"margin: 0 1em 1em 1em" %> <!-- chamar view para novo -->